# Generated by Django 4.2.3 on 2023-07-19 06:54

from django.db import migrations, models
import wagtail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CMSBlogIndexPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("intro", wagtail.fields.RichTextField(blank=True)),
            ],
        ),
    ]
