# Generated by Django 4.2.3 on 2023-07-19 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailimages", "0025_alter_image_file_alter_rendition_file"),
        ("cmsblog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cmsblogindexpage",
            options={"verbose_name_plural": "Cms Blog Posts"},
        ),
        migrations.RemoveField(
            model_name="cmsblogindexpage",
            name="intro",
        ),
        migrations.AddField(
            model_name="cmsblogindexpage",
            name="icon",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
        migrations.AddField(
            model_name="cmsblogindexpage",
            name="name",
            field=models.CharField(default="Title here", max_length=255),
        ),
    ]
